# Generated by Django 5.0.1 on 2024-01-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=75)),
                ('task_description', models.TextField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
